name: deploy

on:
  workflow_dispatch:


jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    #- name: Azure CLI script
    #  uses: azure/CLI@v1
    #  with:
    #    azcliversion: 2.37.0
    #    inlineScript: |
    #      az staticwebapp create -n bestofui5-patch-2 -g github-followers
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.37.0
        inlineScript: |
          echo `GITHUB_SHA_SHORT=$(az staticwebapp secrets list --name bestofui5-patch-2 --query "properties.apiKey"` >> $GITHUB_ENV
           
    #- name: Set env
    #  run: echo `GITHUB_SHA_SHORT=$(az staticwebapp secrets list --name bestofui5-patch-2 --query "properties.apiKey"` >> $GITHUB_ENV
    #- name: test
    #  run : sed -e 's/^"//' -e 's/"$//' <<<"$GITHUB_ENV" 
    - name: run az
      run: az staticwebapp secrets list --name bestofui5-patch-2 --query "properties.apiKey"`
    - uses: gliech/create-github-secret-action@v1
      with:
        name: bestofui5_patch_2
        value: ${{ env.GITHUB_SHA_SHORT }}
        pa_token: ${{ secrets.PAT_TOKEN }}
