name: deploy

on:
  workflow_dispatch:


jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}  
    - name: Set env
      run: echo "azuresecret=$(az staticwebapp secrets list --name bestofui5-patch-2 --query "properties.apiKey")" >> $GITHUB_ENV
    - name: remove quotes
      run : sed -e 's/^"//' -e 's/"$//' <<<"${{ env.azuresecret }}"
            echo "azuresecret=$({{ env.azuresecret }} | tr -d '"')" >> $GITHUB_ENV
    - name: echo
      run: echo "${{ env.azuresecret }}"
    - uses: gliech/create-github-secret-action@v1
      with:
        name: bestofui5_patch_2
        value: ${{ env.azuresecret }}
        pa_token: ${{ secrets.PAT_TOKEN }}
