name: testbranchlabel

on:
  workflow_dispatch:
  pull_request:
    types: [ labeled ]

jobs:
  build:
    if: ${{ github.event.label.name == 'deploy_test' }}
    runs-on: ubuntu-latest

    steps:
    #- uses: actions/checkout@v2
    - name: branch name
      run: echo "$env.GITHUB_HEAD_REF"
    - name: branch
      run: echo "$GITHUB_HEAD_REF"
    - name: test
      run: echo '${{ toJSON(github) }}'
